version: "3"
services:
###############################
#  Setup client container
################################
  webapp:
    build: ./webapp
    container_name: webapp
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - serverapp
###############################
#  Setup node container
################################
  serverapp:
    build: ./server
    container_name: serverapp
    expose:
      - "4000"
    ports:
      - "4000:4000"